_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/defrcn/checkpoints/coco_taco/DEFRCN/faster_rcnn_R_101_FPN_all/model_reset_remove.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 16
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
DATASETS:
  TRAIN: ('taco_30shot_42_train',)
  TEST: ('taco_30shot_42_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (3200,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
INPUT:
  MIN_SIZE_TRAIN: (1024, 1088, 1152, 1216, 1280)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1600
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/content/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 500
OUTPUT_DIR: "/content/drive/MyDrive/defrcn/checkpoints/coco_taco/DEFRCN/30shot_42"